[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"

# Required for OpenZeppelin Foundry Upgrades
extra_output = ["storageLayout"]
extra_output_files = ["storageLayout"]
ast = true
build_info = true
ffi = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
    "forge-std/=lib/forge-std/src/"
]

fs_permissions = [{ access = "read", path = "out" }]
